### ISSUE TITLE
todo!

### ISSUE THREAD

**Issue by fantasyzhjk** [Monodesu/KanonBot#12]
- [x] ppvs
- [x] 成绩（信息）查询功能无法用 at 方法查询
- [x] sudo指令
- [x] 多平台的账号绑定
- [x] custom移植
- [x] 新的成绩面板
- [ ] 兼容onebot12协议
- [x] discord的支持（可能）
- [ ] Highest rank(ppy貌似给了api)
- [x] 重构指令系统（work in progress）

**Comment by Monodesu** [comment]
2024年了，该关了。。。
